---
title: "Michael"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

# Introduction
```{r setup, include=FALSE}
library(tidyverse)
library(babynames)

name_data <- 
  babynames %>% 
  filter(name == "Michael") %>% 
  mutate(sex = case_when(sex == "M" ~ "Male", 
                         sex == "F" ~ "Female"))

# Total number of children
n <- sum(name_data$n)

# most$year is most popular year
# most$n is the number of children that year
# most_sex is whether those children were boys or girls
most <- name_data %>% 
  filter(n == max(n))

most_sex <- most %>% 
  pull("sex") %>% 
  switch("Male" = "boys", "Female" = "girls")

# Has the name been a boy's or girl's name?
sex <-
  name_data %>% 
  group_by(sex) %>% 
  summarise(n = sum(n)) %>% 
  filter(n == max(n)) %>% 
  pull("sex") %>% 
  switch("Male" = "boy's", "Female" = "girl's")
```

## Summary
There have been **`r n`** children named Michael. The name Michael was most popular in `r most$year`, when `r most$n` `r most_sex` were named Michael. Michael is traditionally a `r sex` name.

## Plot
```{r echo=FALSE}
name_data %>% 
  ggplot() +
    geom_ribbon(mapping = aes(x = year, ymax = prop, fill = sex), ymin = 0, alpha = 0.5) +
    labs(title = "Popularity of the name Michael", 
         subtitle = "The proportion of boys and girls named Michael, 1880-2017", 
         caption = "Data from the US Social Security Administration",
         y = "proportion") +
    theme_bw()
```

