## Data Manipulations

```{r DataManipulation}
data <- haven::read_sas("chapter15_example.sas7bdat")

data <- data %>%
  rename_all( ~ str_replace(string = ., pattern=params$endpoint, replacement="outcome")) %>%
  bind_cols(data,.) %>%
  drop_na()


data %>%
  head(10)
```

The data shows post-baseline measurements for subjects on duloxetine and placebo 
(+paroxetine). Although two doses of duloxetine were given in the study
the data has been "anonymised" by randomly sampling from the two different doses.

## Conditional execution of Data Manipulation.
If you see the section named `Data Manipulation` above, then 
this is a separate child document that documents the tasks taken to read in a 
prepare the data for analysis. If that section is missing, then the R code used 
in the Data Manipulation has been `purl`ed and `source`d so that the code is 
still executed prior to running the sections below. We can control appearance
of this section - in this case it only appears if we choose to show aspects of
the report that might be of interest to quantitative reviewers.

## Renaming of the endpoint variable
Each outcome variable is a column in the dataset (tidy principles!) and to make
the report work well with parameterisation, we rename this in the initial
data manipulation to "outcome" so that subsequent tasks can be written 
generically. Alternatively, we could condition on the endpoint selected to 
perform different actions for each, without renaming - for example, if we had
continuous and categorical outcomes.